/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-06-09 15:18:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class fragrance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1717663450034L));
    _jspx_dependants.put("jar:file:/C:/kh/teamproject_Aesop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/aesop/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/kh/teamproject_Aesop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/aesop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/kh/teamproject_Aesop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/aesop/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/1f3107a968.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <title>향수</title>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/head.jsp", out, false);
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        main { margin-top: 100px;}\r\n");
      out.write("        .topmain {\r\n");
      out.write("		height: 360px;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		position: relative;\r\n");
      out.write("		overflow: hidden;\r\n");
      out.write("		}\r\n");
      out.write("		.topmain img { \r\n");
      out.write("			width: 100%;\r\n");
      out.write("		    top: -60px;\r\n");
      out.write("		    position: absolute;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.topmain-text{\r\n");
      out.write("			z-index: 1;\r\n");
      out.write("			position: absolute;\r\n");
      out.write("			top: 100px;\r\n");
      out.write("			color : #fff;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.text25 {\r\n");
      out.write("			font-size: 25px;\r\n");
      out.write("			line-height: 3em;\r\n");
      out.write("			margin-left: 50px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#explore-text {\r\n");
      out.write("			margin-top: 20px;\r\n");
      out.write("			margin-bottom:20px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.text14 {\r\n");
      out.write("			margin-left: 50px;\r\n");
      out.write("			line-height: 1.5em;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.cate-navwrap {\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			height : 70px;\r\n");
      out.write("			background-color: #EBEADE;\r\n");
      out.write("			display: flex;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("			padding-left: 50px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.catelist{\r\n");
      out.write("			display: flex;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.navbar-item {\r\n");
      out.write("			margin-right: 40px; /* 패딩 조정 */\r\n");
      out.write("			line-height: 2em;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.navbar-item:hover {\r\n");
      out.write("			border-bottom: 1px solid #252525;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.explore-tabwrap { \r\n");
      out.write("			width: 100%;\r\n");
      out.write("			height: 280px;\r\n");
      out.write("			overflow: hidden;\r\n");
      out.write("			position: relative;\r\n");
      out.write("		}\r\n");
      out.write("			\r\n");
      out.write("		.explore-tab{\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			display: grid;\r\n");
      out.write("			grid-template-columns: 20% 20% 20% 20% 20%;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.explore-tab2{\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			display: grid;\r\n");
      out.write("			grid-template-columns: 25% 25% 25% 25%;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.explore-tabblock { \r\n");
      out.write("			padding:1px;\r\n");
      out.write("			position: relative;\r\n");
      out.write("		}\r\n");
      out.write("	   \r\n");
      out.write("	    /* 마우스 오버 시 이미지 어둡게 */\r\n");
      out.write("	    \r\n");
      out.write("	    .overlay {\r\n");
      out.write("	        position: absolute;\r\n");
      out.write("	        top: 0;\r\n");
      out.write("	        left: 0;\r\n");
      out.write("	        width: 100%;\r\n");
      out.write("	        height: 100%;\r\n");
      out.write("	        background-color: rgba(0, 0, 0, 0.5);\r\n");
      out.write("	        opacity: 0;\r\n");
      out.write("	        transition: opacity 0.3s ease;\r\n");
      out.write("	        z-index: 0;\r\n");
      out.write("	    }\r\n");
      out.write("	\r\n");
      out.write("	    .explore-tabblock:hover>.overlay {\r\n");
      out.write("	        opacity: 1;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("		.explore-tabblock-tag {\r\n");
      out.write("			position: absolute;\r\n");
      out.write("			margin : 30px;\r\n");
      out.write("			color:#fff;\r\n");
      out.write("			font-weight: 500;\r\n");
      out.write("			z-index: 1;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.explore-tabblock-link {\r\n");
      out.write("			 position: relative;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.explore-tabblock-img img{\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			display: block;\r\n");
      out.write("			transition: opacity 0.3s ease;		\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.explore-tabblock:hover .overlay {\r\n");
      out.write("	        opacity: 1;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    .explore-tabblock:hover .explore-tabblock-img img { transform: scale (1.1);}\r\n");
      out.write("        .fr-prev::after, .fr-next::after {\r\n");
      out.write("            font-family: 'FontAwesome';\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("        .fr-prev::after {\r\n");
      out.write("            content: '\\f104'; /* FontAwesome 왼쪽 화살표 아이콘 */\r\n");
      out.write("        }\r\n");
      out.write("        .fr-next::after {\r\n");
      out.write("            content: '\\f105'; /* FontAwesome 오른쪽 화살표 아이콘 */\r\n");
      out.write("        }\r\n");
      out.write("        .fr-carousel {\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .fr-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            transition: transform 0.5s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .fr-cell {\r\n");
      out.write("            width: 180px;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .fr-cell img { \r\n");
      out.write("            height: 100%; \r\n");
      out.write("            transition: opacity 0.5s ease, transform 0.5s ease; /* 이미지 투명도 전환 애니메이션 */\r\n");
      out.write("        }\r\n");
      out.write("        .fr-cell.active img {\r\n");
      out.write("            transform: scale(1.1); /* 활성화된 슬라이드 이미지를 1.1배 커지도록 설정 */\r\n");
      out.write("        }\r\n");
      out.write("        .button-container {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("        }\r\n");
      out.write("        .fr-prev, .fr-next {\r\n");
      out.write("            background: none;\r\n");
      out.write("            border: none;\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("        }\r\n");
      out.write("        .fr-prev {\r\n");
      out.write("            left: calc(50% - 290px); /* 중앙 이미지의 왼쪽 */\r\n");
      out.write("        }\r\n");
      out.write("        .fr-next {\r\n");
      out.write("            right: calc(50% - 290px); /* 중앙 이미지의 오른쪽 */\r\n");
      out.write("        }\r\n");
      out.write("        .fr-prev:focus, .fr-next:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("        .round-button2 { \r\n");
      out.write("		    width: 110px;\r\n");
      out.write("		    height: 30px;\r\n");
      out.write("		    border-radius: 50px;\r\n");
      out.write("		    line-height: 2em;\r\n");
      out.write("		    border: 1px solid #252525;\r\n");
      out.write("		    text-align: center;\r\n");
      out.write("		}\r\n");
      out.write("        \r\n");
      out.write("        @media (max-width: 1440px) {\r\n");
      out.write("			.topmain { height: 400px;}\r\n");
      out.write("			.topmain img {\r\n");
      out.write("				height: 100%;\r\n");
      out.write("				width: auto;\r\n");
      out.write("				top:0;\r\n");
      out.write("				right: -200px;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"content\">\r\n");
      out.write("			<!-- 헤더 부분 include -->\r\n");
      out.write("		 	<header id=\"header\">\r\n");
      out.write("				");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("			</header> \r\n");
      out.write("			<main class=\"contents\">\r\n");
      out.write("			    <div class=\"topmain\">\r\n");
      out.write("					<div class=\"topmain-text\">\r\n");
      out.write("						<div class=\"text25\">향수</div>\r\n");
      out.write("						<div class=\"text14\">\r\n");
      out.write("							<p>이솝의 바디와 핸드 제품은 효과적인 클렌징, 수분 공급, \r\n");
      out.write("							<br>퍼스널 케어에 따른 고민 완화 등 일상적일 수 있는 경험을 한층 풍성하게 만들어줍니다.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<img alt=\"향수\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/product/fragrance/perfume.png\">\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"cate-navwrap\">\r\n");
      out.write("					<nav class=\"cate-nav\">\r\n");
      out.write("						<ul class=\"catelist\">\r\n");
      out.write("							<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/listAll.do?category=p\" class=\"navbar-item\" title=\"전체\" style=\"border-bottom: 1px solid #252525;\">\r\n");
      out.write("			                    모든\r\n");
      out.write("			                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			                </a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/list.do?category=p&category_sub=1\" class=\"navbar-item ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category_sub eq '1' ? 'active' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" title=\"샴푸\">\r\n");
      out.write("			                    플로럴\r\n");
      out.write("			                </a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/list.do?category=p&category_sub=2\" class=\"navbar-item ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category_sub eq '2' ? 'active' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" title=\"컨디셔너\">\r\n");
      out.write("			                    프레쉬\r\n");
      out.write("			                </a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/list.do?category=p&category_sub=3\" class=\"navbar-item ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category_sub eq '3' ? 'active' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" title=\"트리트먼트\">\r\n");
      out.write("			                    우디\r\n");
      out.write("			                </a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/list.do?category=p&category_sub=4\" class=\"navbar-item ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category_sub eq '4' ? 'active' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" title=\"그루밍\">\r\n");
      out.write("			                    오큘런트\r\n");
      out.write("			                </a></li>\r\n");
      out.write("			                 ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			            </ul>\r\n");
      out.write("					</nav>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"text25\" id=\"explore-text\">유형별 제품 탐색하기</div>\r\n");
      out.write("				<div class=\"explore-tabwrap\">\r\n");
      out.write("			        <div class=\"explore-tab2\">\r\n");
      out.write("			            <div class=\"explore-tabblock\">\r\n");
      out.write("			                <a class=\"explore-tabblock-link\" href=\"\">\r\n");
      out.write("			                	<div class=\"overlay\"></div>\r\n");
      out.write("			                    <div class=\"explore-tabblock-tag\">플로럴</div>\r\n");
      out.write("			                    <div class=\"explore-tabblock-img\">\r\n");
      out.write("			                        <img alt=\"block1\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/product/fragrance/floral.png\">\r\n");
      out.write("			                        <div class=\"overlay\"></div>\r\n");
      out.write("			                    </div>\r\n");
      out.write("			                </a>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div class=\"explore-tabblock\">\r\n");
      out.write("			                <a class=\"explore-tabblock-link\" href=\"\">\r\n");
      out.write("			                    <div class=\"explore-tabblock-tag\">프레쉬</div>\r\n");
      out.write("			                    <div class=\"explore-tabblock-img\">\r\n");
      out.write("			                        <img alt=\"block2\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/product/fragrance/fresh.png\">\r\n");
      out.write("			                        <div class=\"overlay\"></div>\r\n");
      out.write("			                    </div>\r\n");
      out.write("			                </a>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div class=\"explore-tabblock\">\r\n");
      out.write("			                <a class=\"explore-tabblock-link\" href=\"\">\r\n");
      out.write("			                    <div class=\"explore-tabblock-tag\">우디</div>\r\n");
      out.write("			                    <div class=\"explore-tabblock-img\">\r\n");
      out.write("			                        <img alt=\"block3\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/product/fragrance/woody.png\">\r\n");
      out.write("			                        <div class=\"overlay\"></div>\r\n");
      out.write("			                    </div>\r\n");
      out.write("			                </a>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div class=\"explore-tabblock\">\r\n");
      out.write("			                <a class=\"explore-tabblock-link\" href=\"\">\r\n");
      out.write("			                    <div class=\"explore-tabblock-tag\">오큘런트</div>\r\n");
      out.write("			                    <div class=\"explore-tabblock-img\">\r\n");
      out.write("			                        <img alt=\"block4\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/product/fragrance/oculant.png\">\r\n");
      out.write("			                        <div class=\"overlay\"></div>\r\n");
      out.write("			                    </div>\r\n");
      out.write("			                </a>\r\n");
      out.write("			            </div>\r\n");
      out.write("			        </div>\r\n");
      out.write("			    </div>\r\n");
      out.write("                <div class=\"text-ofl\">Compare our Fragrances</div>\r\n");
      out.write("                <div class=\"fr-carousel_wrap\">\r\n");
      out.write("                    <div class=\"fr-carousel\">\r\n");
      out.write("                        <!-- <div class=\"button-container\">\r\n");
      out.write("                            <button class=\"fr-prev\"></button>\r\n");
      out.write("                            <button class=\"fr-next\"></button>\r\n");
      out.write("                        </div> -->\r\n");
      out.write("                        <ul class=\"fr-container\">\r\n");
      out.write("                            <li class=\"fr-cell\" data-index=\"0\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/product/fragrance/Tacit.png\" alt=\"테싯\"></li>\r\n");
      out.write("                            <li class=\"fr-cell\" data-index=\"1\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/product/fragrance/Karst.png\" alt=\"카르스트\"></li>\r\n");
      out.write("                            <li class=\"fr-cell\" data-index=\"2\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/product/fragrance/Eremia.png\" alt=\"에레미야\"></li>\r\n");
      out.write("                            <li class=\"fr-cell\" data-index=\"3\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/product/fragrance/Gloam.png\" alt=\"글롬\"></li>\r\n");
      out.write("                            <li class=\"fr-cell\" data-index=\"4\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/product/fragrance/Rozu.png\" alt=\"로즈\"></li>\r\n");
      out.write("                            <li class=\"fr-cell\" data-index=\"5\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/product/fragrance/Marrakech.png\" alt=\"마라케시\"></li>\r\n");
      out.write("                            <li class=\"fr-cell\" data-index=\"6\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/product/fragrance/Hwyl.png\" alt=\"휠\"></li>\r\n");
      out.write("                            <li class=\"fr-cell\" data-index=\"7\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/product/fragrance/Eidesis.png\" alt=\"이더시스\"></li>\r\n");
      out.write("                            <li class=\"fr-cell\" data-index=\"8\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/product/fragrance/Miraceti.png\" alt=\"미라세티\"></li>\r\n");
      out.write("                            <li class=\"fr-cell\" data-index=\"9\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/product/fragrance/Ouranon.png\" alt=\"우라논\"></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                	<ul class=\"note-Comparison\">\r\n");
      out.write("                            <li class=\"note-Comparison-info\" aria-current=\"\" data-index=\"0\">\r\n");
      out.write("                            	<h3>테싯 오 드 퍼퓸</h3>\r\n");
      out.write("                            	<p>유자, 베티버, 바질</p>\r\n");
      out.write("                            	<p>2사이즈</p>\r\n");
      out.write("                            	<p>170,000부터</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"note-Comparison-info\" aria-current=\"\" data-index=\"1\">\r\n");
      out.write("                            	<h3>카르스트 오 드 퍼퓸</h3>\r\n");
      out.write("			                	<p>주니퍼, 쿠민, 샌달우드</p>\r\n");
      out.write("			                	<p>50 mL</p>\r\n");
      out.write("			                	<p>225,000</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"note-Comparison-info\" aria-current=\"\" data-index=\"2\">\r\n");
      out.write("                            	<h3>에레미아 오 드 퍼퓸</h3>\r\n");
      out.write("                            	<p>갈바눔, 아이리스, 유자</p>\r\n");
      out.write("                            	<p>50 mL</p>\r\n");
      out.write("			                	<p>225,000</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"note-Comparison-info\" aria-current=\"\" data-index=\"3\">\r\n");
      out.write("                            	<h3>에레미아 오 드 퍼퓸</h3>\r\n");
      out.write("                            	<p>갈바눔, 아이리스, 유자</p>\r\n");
      out.write("                            	<p>2사이즈</p>\r\n");
      out.write("                            	<p>170,000부터</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"note-Comparison-info\" aria-current=\"\" data-index=\"4\">\r\n");
      out.write("                            	<h3>테싯 오 드 퍼퓸</h3>\r\n");
      out.write("                            	<p>유자, 베티버, 바질</p>\r\n");
      out.write("                            	<p>2사이즈</p>\r\n");
      out.write("                            	<p>170,000부터</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"note-Comparison-info\" aria-current=\"\" data-index=\"5\">\r\n");
      out.write("                            	<h3>테싯 오 드 퍼퓸</h3>\r\n");
      out.write("                            	<p>유자, 베티버, 바질</p>\r\n");
      out.write("                            	<p>2사이즈</p>\r\n");
      out.write("                            	<p>170,000부터</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"note-Comparison-info\" aria-current=\"\" data-index=\"6\">\r\n");
      out.write("                            	<h3>테싯 오 드 퍼퓸</h3>\r\n");
      out.write("                            	<p>유자, 베티버, 바질</p>\r\n");
      out.write("                            	<p>2사이즈</p>\r\n");
      out.write("                            	<p>170,000부터</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"note-Comparison-info\" aria-current=\"\" data-index=\"7\">\r\n");
      out.write("                            	<h3>테싯 오 드 퍼퓸</h3>\r\n");
      out.write("                            	<p>유자, 베티버, 바질</p>\r\n");
      out.write("                            	<p>2사이즈</p>\r\n");
      out.write("                            	<p>170,000부터</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"note-Comparison-info\" aria-current=\"\" data-index=\"8\">\r\n");
      out.write("                            	<h3>테싯 오 드 퍼퓸</h3>\r\n");
      out.write("                            	<p>유자, 베티버, 바질</p>\r\n");
      out.write("                            	<p>2사이즈</p>\r\n");
      out.write("                            	<p>170,000부터</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"note-Comparison-info\" aria-current=\"\" data-index=\"9\">\r\n");
      out.write("                            	<h3>테싯 오 드 퍼퓸</h3>\r\n");
      out.write("                            	<p>유자, 베티버, 바질</p>\r\n");
      out.write("                            	<p>2사이즈</p>\r\n");
      out.write("                            	<p>170,000부터</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("        </main>\r\n");
      out.write("        <footer>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("		</footer>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        const container = $('.fr-container');\r\n");
      out.write("        const cells = $('.fr-cell');\r\n");
      out.write("        const comparisonInfo = $('.note-Comparison-info');\r\n");
      out.write("        const cellWidth = cells.outerWidth();\r\n");
      out.write("        const totalCells = cells.length;\r\n");
      out.write("        let currentIndex = 0; // index 0이 기본으로 활성화\r\n");
      out.write("\r\n");
      out.write("        function updateOpacity() {\r\n");
      out.write("            cells.each(function(index) {\r\n");
      out.write("                $(this).find('img').css('opacity', index === currentIndex ? '1' : '0.5');\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function updateActiveClass() {\r\n");
      out.write("            cells.removeClass('active'); // 모든 슬라이드의 active 클래스 제거\r\n");
      out.write("            cells.eq(currentIndex).addClass('active'); // 현재 인덱스의 슬라이드에 active 클래스 추가\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function updateComparisonInfo() {\r\n");
      out.write("            comparisonInfo.each(function(index) {\r\n");
      out.write("                if (index === currentIndex) {\r\n");
      out.write("                    $(this).addClass('active').show(); // 현재 인덱스의 Comparison-info에 active 클래스 추가하고 표시\r\n");
      out.write("                } else {\r\n");
      out.write("                    $(this).removeClass('active').hide(); // 나머지 요소는 active 클래스 제거하고 숨김\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function updateCarousel() {\r\n");
      out.write("            const offset = -(currentIndex * cellWidth - ($('.fr-carousel').width() / 2 - cellWidth / 2));\r\n");
      out.write("            container.css('transform', 'translateX(' + offset + 'px)');\r\n");
      out.write("            updateOpacity();\r\n");
      out.write("            updateComparisonInfo(); // 활성화된 슬라이드에 맞춰 Comparison info 업데이트\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $('.fr-prev').click(function() {\r\n");
      out.write("            currentIndex = Math.max(currentIndex - 1, 0); // 한 칸씩 이동하도록 수정\r\n");
      out.write("            updateCarousel();\r\n");
      out.write("            updateActiveClass();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('.fr-next').click(function() {\r\n");
      out.write("            currentIndex = Math.min(currentIndex + 1, totalCells - 1); // 한 칸씩 이동하도록 수정\r\n");
      out.write("            updateCarousel();\r\n");
      out.write("            updateActiveClass();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // fr-cell 클릭 시 활성화\r\n");
      out.write("        cells.click(function() {\r\n");
      out.write("            currentIndex = $(this).data('index');\r\n");
      out.write("            updateCarousel();\r\n");
      out.write("            updateActiveClass();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(window).resize(function() {\r\n");
      out.write("            updateCarousel();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        updateCarousel(); // 초기 상태 업데이트\r\n");
      out.write("        updateActiveClass(); // 초기 상태에서 active 클래스 추가\r\n");
      out.write("        updateComparisonInfo(); // 초기 상태에서 모든 Comparison-info 요소를 보여주고, 활성화된 요소만 업데이트\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/product/fragrance.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path2");
      // /WEB-INF/views/product/fragrance.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/product/fragrance.jsp(6,0) '${pageContext.servletContext.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/product/fragrance.jsp(245,23) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty categoryName}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							     	");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("							    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/product/fragrance.jsp(261,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${semail.equals('admin@aesop.com') }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				                <div class=\"round-button2\"><li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/product/insert.do\" class=\"button is-danger\">상품 등록</a></li></div>\r\n");
          out.write("			                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
