/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-06-07 06:44:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/Leeangie/teamproject_Aesop_spring2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/aesop/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1714616166831L));
    _jspx_dependants.put("jar:file:/D:/Leeangie/teamproject_Aesop_spring2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/aesop/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/Leeangie/teamproject_Aesop_spring2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/aesop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<!DOCTYPE>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("	<title>JOIN</title>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/head.jsp", out, false);
      out.write("\n");
      out.write("	<style>\n");
      out.write("		#join-fullwrap{\n");
      out.write("            width: 100%;\n");
      out.write("            height: 900px;\n");
      out.write("            background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/login/login_image.png);\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            background-repeat: no-repeat;\n");
      out.write("            background-size: 100% auto;\n");
      out.write("            background-position: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #join-window {\n");
      out.write("            width: 560px;\n");
      out.write("            height: 85%;\n");
      out.write("            background-color: #FFFEF2;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            margin-top: 50px;\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #join-table {\n");
      out.write("            clear: both;\n");
      out.write("            width: 400px;\n");
      out.write("            height: 700px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .join-input {\n");
      out.write("            border: 0;\n");
      out.write("            line-height: 3em;\n");
      out.write("            border-bottom: 1px solid #C5C5C5;\n");
      out.write("            background-color: transparent;\n");
      out.write("            width: 400px;\n");
      out.write("        }\n");
      out.write("        .join-input:focus { \n");
      out.write("            cursor: text; \n");
      out.write("            outline: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .square-button {\n");
      out.write("            width: 190px;\n");
      out.write("            height: 44px;\n");
      out.write("            background-color: #252525;\n");
      out.write("            color: #FFFEF2;\n");
      out.write("            border: 1px solid #252525;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            margin-right: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .square-button-fa {\n");
      out.write("            width: 190px;\n");
      out.write("            height: 44px;\n");
      out.write("            background-color: transparent;\n");
      out.write("            color: #252525;\n");
      out.write("            border: 1px solid #252525;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .square-button-fa:hover { \n");
      out.write("            background-color: #F6F5E8;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .square-button-fa2:hover { \n");
      out.write("            background-color: #F6F5E8;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .square-button:hover {\n");
      out.write("            background-color: black;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .text18 { \n");
      out.write("            height: 40px;\n");
      out.write("            font-size: 18px;\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #text24 {\n");
      out.write("            font-size: 24px;\n");
      out.write("            height: 80px;\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .square-button {\n");
      out.write("            width: 400px;\n");
      out.write("            height: 44px;\n");
      out.write("            background-color: #252525;\n");
      out.write("            color: #FFFEF2;\n");
      out.write("            border: 1px solid #252525;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            margin-top: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .term {\n");
      out.write("            width: 400px;\n");
      out.write("            height: 70px;\n");
      out.write("            overflow-y:auto;\n");
      out.write("            border: 1px solid #252525;            \n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-check-label { \n");
      out.write("            line-height: 3em;\n");
      out.write("        }\n");
      out.write("	</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"content\">\n");
      out.write("        <!-- 헤더 부분 include -->\n");
      out.write("		<header id=\"hd\" class=\"container is-fullhd\">\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\n");
      out.write("		</header>\n");
      out.write("        <main>\n");
      out.write("            <div id=\"join-fullwrap\">\n");
      out.write("                <div id=\"join-window\">\n");
      out.write("            	<form name=\"frm1\" id=\"frm1\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/joinPro.do\" method=\"post\" onsubmit=\"return joinCheck(this)\">\n");
      out.write("                	<table id=\"join-table\">\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td id=\"text24\">회원가입</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" name=\"name\" id=\"name\" placeholder=\"이름 입력\" maxlength=\"40\" required class=\"join-input\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"email\" name=\"email\" id=\"email\" placeholder=\"이메일 입력\" pattern=\"^\\w+((\\.\\w+)?)+@\\w+.?\\w+\\.\\w+$\" maxlength=\"80\" required class=\"join-input\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"password\" name=\"pw\" id=\"pw\" placeholder=\"비밀번호\" required class=\"join-input\" pattern=\"^(?=.*[A-Za-z])(?=.*\\d)(?=.*[$@$!%*#?&])[A-Za-z\\d$@$!%*#?&]{8,12}$\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"password\" name=\"pw2\" id=\"pw2\" placeholder=\"비밀번호 확인 입력\" maxlength=\"12\" class=\"join-input\" required pattern=\"^(?=.*[A-Za-z])(?=.*\\d)(?=.*[$@$!%*#?&])[A-Za-z\\d$@$!%*#?&]{8,12}$\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>\n");
      out.write("                                        <div class=\"form-check\">\n");
      out.write("                                            <input type=\"checkbox\" id=\"ck_item1\" name=\"ck_item1\" class=\"form-check-input\" required>\n");
      out.write("                                            <label for=\"ck_item1\" class=\"form-check-label\">본인은 만 14세 이상입니다 (필수)</label>\n");
      out.write("                                        </div>\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>\n");
      out.write("                                        <div class=\"form-check\">\n");
      out.write("                                            <input type=\"checkbox\" id=\"ck_item2\" name=\"ck_item2\" class=\"form-check-input\" required>\n");
      out.write("                                            <label for=\"ck_item2\" class=\"form-check-label\">이용 약관에 동의합니다 (필수)</label>\n");
      out.write("                                        </div>\n");
      out.write("                                        <article class=\"term\">\n");
      out.write("                                            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "term2.jsp", out, false);
      out.write("\n");
      out.write("                                        </article>\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>\n");
      out.write("                                        <div class=\"form-check\">\n");
      out.write("                                            <input type=\"checkbox\" id=\"ck_item3\" name=\"ck_item3\" class=\"form-check-input\" required>\n");
      out.write("                                            <label for=\"ck_item2\" class=\"form-check-label\">개인정보 수집 및 이용조건에 동의합니다 (필수)</label>\n");
      out.write("                                        </div>\n");
      out.write("                                        <article class=\"term\">\n");
      out.write("                                            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "term3.jsp", out, false);
      out.write("\n");
      out.write("                                        </article>\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td><label onclick=\"protocol()\" class=\"form-check-label\"><strong>전체 약관에 동의</strong></label></td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td><button type=\"button\" class=\"square-button\" id=\"in_btn1\">회원가입</button></td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("		            </form>\n");
      out.write("		            <script>\n");
      out.write("					    var ck_item1 = document.getElementById(\"ck_item1\")\n");
      out.write("					    var ck_item2 = document.getElementById(\"ck_item2\");\n");
      out.write("					    var ck_item3 = document.getElementById(\"ck_item3\");\n");
      out.write("					    var in_btn1 = document.getElementById(\"in_btn1\");\n");
      out.write("					    in_btn1.addEventListener(\"click\", function(event){\n");
      out.write("					        event.preventDefault(); // 버튼의 기본 동작 중지\n");
      out.write("					\n");
      out.write("					        if(ck_item1.checked && ck_item2.checked && ck_item3.checked && validateInputs()){\n");
      out.write("					            document.getElementById(\"frm1\").submit(); // 폼 제출\n");
      out.write("					        } else {\n");
      out.write("					            alert(\"필수항목을 모두 체크하고, 입력 사항을 모두 채워주세요.\");\n");
      out.write("					        }\n");
      out.write("					    });\n");
      out.write("					\n");
      out.write("					    function protocol(){\n");
      out.write("					        ck_item2.checked = true;\n");
      out.write("					        ck_item3.checked = true;\n");
      out.write("					    }\n");
      out.write("					\n");
      out.write("					    function validateInputs() {\n");
      out.write("					        var name = document.getElementById(\"name\").value.trim();\n");
      out.write("					        var email = document.getElementById(\"email\").value.trim();\n");
      out.write("					        var pw = document.getElementById(\"pw\").value.trim();\n");
      out.write("					        var pw2 = document.getElementById(\"pw2\").value.trim();\n");
      out.write("					\n");
      out.write("					        // 각 필드가 비어 있는지 확인\n");
      out.write("					        if (name === \"\" || email === \"\" || pw === \"\" || pw2 === \"\") {\n");
      out.write("					            return false;\n");
      out.write("					        }\n");
      out.write("					\n");
      out.write("					        return true;\n");
      out.write("					    }\n");
      out.write("					</script>\n");
      out.write("		            \n");
      out.write("		            <script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("	        	</div>\n");
      out.write("	        </div>\n");
      out.write("	</main>\n");
      out.write("	<footer>\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\n");
      out.write("	</footer>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/member/join.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path2");
      // /WEB-INF/views/member/join.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/join.jsp(5,0) '${pageContext.servletContext.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
